version: "3.9"

services:
  furan.xyz:
    container_name: furan.xyz
    restart: "always"
    image: nginx:stable-alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
