version: "3.9"

services:
  furan.xyz:
    container_name: furan.xyz
    image: nginx:stable-alpine
    restart: "always"
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/furan.xyz/fullchain.pem:/etc/letsencrypt/live/furan.xyz/fullchain.pem
      - /etc/letsencrypt/live/furan.xyz/privkey.pem:/etc/letsencrypt/live/furan.xyz/privkey.pem

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
