version: "3.9"

services:
  furan.xyz:
    container_name: furan.xyz
    
    image: ngekaworu/furan.xyz
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
