version: "3.9"

services:
  furan.xyz:
    container_name: furan.xyz
    
    image: ngekaworu/furan.xyz
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/archive/furan.xyz/cert1.pem:/etc/letsencrypt/live/furan.xyz/cert.pem
      - /etc/letsencrypt/archive/furan.xyz/chain1.pem:/etc/letsencrypt/live/furan.xyz/chain.pem
      - /etc/letsencrypt/archive/furan.xyz/fullchain1.pem:/etc/letsencrypt/live/furan.xyz/fullchain.pem
      - /etc/letsencrypt/archive/furan.xyz/privkey1.pem:/etc/letsencrypt/live/furan.xyz/privkey.pem

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
